services:
  app-service:
    image: kenesparta/lgr-app-service
    restart: "always"
    environment:
      AUTH_SERVICE_HOST: ${AUTH_SERVICE_HOST}
      GRPC_AUTH_SERVICE_HOST: ${GRPC_AUTH_SERVICE_HOST}
      CAPTCHA_SITE_KEY: ${CAPTCHA_SITE_KEY}
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
    ports:
      - "8000:8000"
